baseurl = "https://bldn.se/"
copyright = "All rights reserved - 2017"
#disqusshortname = "vjeantet"
languagecode = "en-GB"
paginate = 5
pluralizelisttitles = true
theme = "casper"
title = "Jonas Bolldén"

#[[menu.main]]
#	identifier="about"
#	name = "About"
#	#pre = "<h3>Follow me</h3>"
#	url = "/about/"
#	weight = 100
[[menu.main]]
	identifier="resume"
	name = "Résumé"
	url = "https://bldn.se/resume/"
	weight = -110
[[menu.main]]
	identifier = "blog"
	name = "Blog"
	url = "/"
	weight = -120

[params]
	author = "Jonas Bolldén"
	authorlocation = "Luleå, Sweden"
	authorwebsite = "https://bldn.se"
	bio = "By trade a pragmatic IT-human with a burning passion for Scrum; by choice a husband, shooter, and servant-leader."

	cover = "/i_mg/backdrops/Linkoping_GreyTable_2016-05-01_1400x1050.jpg"
	description = "thoughts, stories, ideas"
	hideHUGOSupport = false
	#logo = ""

	googleAnalyticsUserID = "UA-48225347-1"

	linkedinName = "jonasbollden"
	githubName = "jonasbollden"
	facebookName = "jonasbollden"
	twitterName = "jonasbollden"
	instagramName = "jonasbollden"

[permalinks]
	post = "/:year/:month/:day/:slug/"

[sitemap]
	ChangeFreq = ""
	Filename = "sitemap.xml"
	Priority = "-1"
