BaseURL = "https://bldn.se/"
Copyright = " - CC BY-SA 4.0"
DisqusShortname = "bldn-se"
Languagecode = "en"
Paginate = 5
Title = "Jonas Bolldén"

# CLI flags
pluralizeListTitles = true
theme = "casper"

[[menu.main]]
	identifier="resume"
	name = "Résumé"
	url = "https://bldn.se/cv/"
	weight = -110
[[menu.main]]
	identifier = "blog"
	name = "Blog"
	url = "/"
	weight = -120

[params]
	author = "Jonas Bolldén"
	authorlocation = "Luleå, Sweden"
	authorwebsite = "https://bldn.se"
	bio = "By trade a pragmatic IT-human with a burning passion for Scrum; by choice a husband, shooter, and servant-leader."

	cover = "https://static.bldn.se/img/backdrops/Linkoping_GreyTable_2016-05-01_1400x1050.jpg"
	description = "thoughts, stories, ideas"
	hideHUGOSupport = false
	# logo = ""

	googleAnalyticsUserID = "UA-48225347-1"

	linkedinName = "jonasbollden"
	githubName = "jonasbollden"
	facebookName = "jonasbollden"
	twitterName = "jonasbollden"
	instagramName = "jonasbollden"

	customCSS = ["css/custom.css"]

[permalinks]
	post = "/:year/:month/:day/:slug/"

[sitemap]
	ChangeFreq = ""
	Filename = "sitemap.xml"
	Priority = "-1"
