baseurl = "https://blog.bldn.se/"
languageCode = "en-us"
title = "blog.bldn.se"
theme = "casper"
disqusShortname = "blogbldnse" 

[params]
	description = "thoughts, stories, ideas"
	author = "Jonas Bolldén"
	bio = "By trade a pragmatic IT-human with a burning passion for Scrum; by choice a husband, shooter, and servant-leader."
	location = "Luleå, Sweden"

[permalinks]
	post = "/:year/:month/:day/:slug/"

[[menu.main]]
	name = "Home"
	weight = -110
	url = "/"
[[menu.main]]
	name = "About"
	weight = -100
	identifier = "about"
	url = "/about/"
[[menu.main]]
	name = "CV"
	weight = -100
	identifier = "cv"
	url = "//bldn.se/cv/"
