baseurl = "//blog.bldn.se/"
languageCode = "en-us"
title = "blog.bldn.se"
theme = "casper"
disqusShortname = "blogbldnse" 

[params]
	cover = "//static.bldn.se/img/backdrops/Linkoping_GreyTable_2016-05-01_1400x1050.jpg"
    favicon = "//bldn.se/favicon.ico"
	description = "thoughts, stories, ideas"
	googleAnalyticsUserID = "UA-48225347-2"

	author = "Jonas Bolldén"
	bio = "By trade a pragmatic IT-human with a burning passion for Scrum; by choice a husband, shooter, and servant-leader."
	location = "Luleå, Sweden"
	linkedinName = "jonasbollden"
	githubName = "jonasbollden"
	facebookName = "jonasbollden"
	twitterName = "jonasbollden"
	instagramName = "jonasbollden"

[permalinks]
	post = "/:year/:month/:day/:slug/"

[[menu.main]]
	name = "Home"
	weight = -110
	url = "/"
[[menu.main]]
	name = "Profile"
	weight = -100
	identifier = "profile"
	url = "/profile/"
[[menu.main]]
	name = "About"
	weight = -90
	identifier = "about"
	url = "/about/"
[[menu.main]]
	name = "CV"
	weight = -80
	identifier = "cv"
	url = "https://bldn.se/cv/"
