title = "Jonas Bolldén"
baseURL = "https://www.bldn.se"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = "https://www.facebook.com/jonasbollden"
  twitter = "https://twitter.com/jonasbollden"
  instagram = "https://www.instagram.com/jonasbollden/"
  youtube = ""
  github = "https://github.com/jonasbollden"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jonasbollden/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/backdrops/Norrbotten_PanoramaMire_2017-07-26_1584x424.jpg"
  recent_posts_number = 5
  show_reading_time = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "posts"
    url = "/posts/"
    weight = -130
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "categories"
    url = "/categories/"
    weight = -120
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "tags"
    url = "/tags/"
    weight = -110
